create table TB_TABELA_IMPOSTO_RENDA (ID bigint generated by default as identity (start with 1), NUM_DIAS bigint, PCT_ALIQUOTA numeric(19,2), ID_TIPO_IMPOSTO_RENDA bigint, primary key (ID));
create table TB_TIPO_IMPOSTO_RENDA (ID bigint generated by default as identity (start with 1), CODIGO varchar(255), DESCRICAO varchar(255), primary key (ID));
alter table TB_TABELA_IMPOSTO_RENDA add constraint FK_6gb22ojhuru3hcnwimmo90lkl foreign key (ID_TIPO_IMPOSTO_RENDA) references TB_TIPO_IMPOSTO_RENDA
insert into TB_TIPO_IMPOSTO_RENDA (ID, CODIGO, DESCRICAO) values (default, 'RF', 'Renda Fixa');
insert into TB_TABELA_IMPOSTO_RENDA (ID, ID_TIPO_IMPOSTO_RENDA, NUM_DIAS, PCT_ALIQUOTA) values (default, 1, 0, 22.5);
insert into TB_TABELA_IMPOSTO_RENDA (ID, ID_TIPO_IMPOSTO_RENDA, NUM_DIAS, PCT_ALIQUOTA) values (default, 1, 180, 20);
insert into TB_TABELA_IMPOSTO_RENDA (ID, ID_TIPO_IMPOSTO_RENDA, NUM_DIAS, PCT_ALIQUOTA) values (default, 1, 360, 17.5);
insert into TB_TABELA_IMPOSTO_RENDA (ID, ID_TIPO_IMPOSTO_RENDA, NUM_DIAS, PCT_ALIQUOTA) values (default, 1, 720, 15);