create table CA_AREA_COMP_CONTABIL (
    ID_AREA_COMP_CONTABIL bigint generated by default as identity (start with 1),
    DT_FIM_VIGENCIA date,
    DT_INICIO_VIGENCIA date not null,
    VERSAO bigint not null,
    ID_CONTROLE_IMPORTACAO bigint,
    ID_AREA_NEGOCIO bigint,
    ID_COMPONENTE_CONTABIL bigint,
    primary key (ID_AREA_COMP_CONTABIL)
);