insert into TB_TIPO_IMPOSTO_RENDA (ID, CODIGO, DESCRICAO) values (default, 'RF', 'Renda Fixa');
insert into TB_TABELA_IMPOSTO_RENDA (ID, ID_TIPO_IMPOSTO_RENDA, NUM_DIAS, PCT_ALIQUOTA) values (default, 1, 0, 22.5);
insert into TB_TABELA_IMPOSTO_RENDA (ID, ID_TIPO_IMPOSTO_RENDA, NUM_DIAS, PCT_ALIQUOTA) values (default, 1, 180, 20);
insert into TB_TABELA_IMPOSTO_RENDA (ID, ID_TIPO_IMPOSTO_RENDA, NUM_DIAS, PCT_ALIQUOTA) values (default, 1, 360, 17.5);
insert into TB_TABELA_IMPOSTO_RENDA (ID, ID_TIPO_IMPOSTO_RENDA, NUM_DIAS, PCT_ALIQUOTA) values (default, 1, 720, 15);